# Generated by Django 3.1.2 on 2021-01-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=64)),
                ('adress', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=128)),
                ('lastName', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('phoneNumber', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=64)),
                ('adress', models.CharField(max_length=256)),
            ],
        ),
    ]
