# Generated by Django 3.1.2 on 2021-01-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19callcenter', '0002_auto_20210121_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='symptoms',
            field=models.CharField(default='', max_length=256),
        ),
    ]
